"#version 330 core\n"
"out vec4 color;"
""
"uniform vec4 rect_color;"
"uniform sampler2D texture1;"
"in vec2 tex_coords;"
""
"flat in int use_texture;"
"const float offset = 1.0/512;"
"const vec2 offsets[9] = vec2[]("
"        vec2(-offset, offset),"
"        vec2(0.0f,    offset),"
"        vec2(offset,  offset),"
"        vec2(-offset, 0.0f),"
"        vec2(0.0f,    0.0f),"
"        vec2(offset,  0.0f),"
"        vec2(-offset, -offset),"
"        vec2(0.0f,    -offset),"
"        vec2(offset,  -offset)"
"    );"
"const float kernel[9] = float[]("
"    0.0625, 0.125, 0.0625,"
"    0.125,  0.25,  0.125,"
"    0.0625, 0.125, 0.0625"
");"
"void main()"
"{"
"   if (use_texture == 1)"
"   {"
"       vec3 fin_col = vec3(0.0f);"
"       for(int i = 0; i < 9; i++)"
"           fin_col += vec3(texture(texture1, tex_coords.st + offsets[i]) * kernel[i]);"
"       color = vec4(mix(fin_col, rect_color.xyz, rect_color.w), 1.0);"
"   }"
"   else"
"   {"
"       color = rect_color;"
"   }"
"}"
