"#version 330 core\n"
"layout (location = 0) in vec3 v;"
""
"out vec3 tex_coords;"
""
"uniform mat4 proj;"
"uniform mat4 view;"
""
"void main()"
"{"
"    tex_coords = v;"
""
"    vec4 pos = proj * view * vec4(v, 1.f);"
"    gl_Position = pos.xyww;"
"}"
