"#version 330 core\n"
"layout (location = 0) in vec3 v;"
""
"uniform mat4 model;"
"uniform mat4 view;"
"uniform mat4 proj;"
""
"void main()"
"{"
"    gl_Position = proj * view * model * vec4(v, 1.0);"
"}"