"#version 330 core\n"
"layout (location = 0) in vec3 v;"
""
"uniform mat4 model;"
""
"layout (std140) uniform GlobalAttributes"
"{"
"   mat4 view;"
"   mat4 proj;"
"   vec3 cam_pos;"
"};"
""
"void main()"
"{"
"    gl_Position = proj * view * model * vec4(v, 1.0);"
"}"