"#version 330 core\n"
""
"in vec4 gColor;"
"in vec2 gTextureCoord;"
""
"uniform sampler2D sprite;"
"uniform int use_texture;"
""
"out vec4 color;"
""
"void main(){"
"   color = gColor;"
"   if (use_texture == 1)"
"	    color *= texture(sprite, gTextureCoord).rgba;"
"   if (color.a <= 0.05)"
"       discard;"
"}"
