#ifndef PX_CG_CONFIG_HPP
#define PX_CG_CONFIG_HPP

#ifndef COMPUTE_SHADER_WORK_GROUP_SIZE
#define COMPUTE_SHADER_WORK_GROUP_SIZE 256
#endif

#ifndef WATER_FOUNTAIN_MAX_PARTICLES
#define WATER_FOUNTAIN_MAX_PARTICLES 100000
#endif

#ifndef FIRWORKS_MAX_PARTICLES // for each firework
#define FIRWORKS_MAX_PARTICLES 10000
#endif
#ifndef FIREWORKS_TRAIL_RATE // number of particles left as trail each second
#define FIREWORKS_TRAIL_RATE 50
#endif
#ifndef FIRWORKS_AMOUNT
#define FIRWORKS_AMOUNT 6
#endif

#ifndef GALAXY_MAX_PARTICLES_CUDA
#define GALAXY_MAX_PARTICLES_CUDA 100000
#endif
#ifndef GALAXY_MAX_PARTICLES_COMPUTE_SHADER
#define GALAXY_MAX_PARTICLES_COMPUTE_SHADER 16000
#endif

#ifndef BENCHMARK_MAX_PARTICLES_COMPUTE_SHADER
#define BENCHMARK_MAX_PARTICLES_COMPUTE_SHADER 100000
#endif
#ifndef BENCHMARK_MAX_PARTICLES_TRANSFORM_FEEDBACK
#define BENCHMARK_MAX_PARTICLES_TRANSFORM_FEEDBACK 3000000
#endif
#ifndef BENCHMARK_MAX_PARTICLES_SIMPLE_INSTANCING
#define BENCHMARK_MAX_PARTICLES_SIMPLE_INSTANCING 100000
#endif
#ifndef BENCHMARK_MAX_PARTICLES_SIMPLE_GEOMETRY_SHADER
#define BENCHMARK_MAX_PARTICLES_SIMPLE_GEOMETRY_SHADER 100000
#endif

#endif // PX_CG_CONFIG_HPP
