"#version 330 core\n"
"layout (location = 0) in vec3 pos;"
"layout (location = 1) in vec2 scal_rot;"
"layout (location = 2) in vec4 color;"
"layout (location = 4) in vec2 uv_offset;"
""
"out VS_OUT"
"{"
"   vec2 scal_rot;"
"   vec4 color;"
"   vec2 uv_offset;"
"} primitive;"
""
"void main()"
"{"
"   gl_Position = vec4(pos.xyz, 1.f);"
"   primitive.scal_rot = scal_rot;"
"   primitive.color = color;"
"   primitive.uv_offset = uv_offset;"
"}"
